class GroceryCatalog {
  static const Map<String, List<String>> itemsByCategory = {
    'Produce': [
      'Apples',
      'Bananas',
      'Oranges',
      'Lettuce',
      'Tomatoes',
      'Potatoes',
      'Onions',
      'Garlic',
      'Carrots',
      'Broccoli',
      'Spinach',
      'Avocado',
      'Strawberries',
      'Blueberries',
      'Cucumbers',
      'Bell Peppers',
      'Lemons',
      'Limes',
      'Grapes',
      'Mushrooms',
      'Kale',
      'Zucchini',
      'Eggplant',
      'Green Beans',
      'Sweet Potatoes',
      'Cauliflower',
      'Celery',
      'Pineapple',
      'Watermelon',
      'Cantaloupe',
      'Pears',
      'Peaches',
      'Plums',
      'Nectarines',
      'Kiwi',
      'Pomegranate',
      'Asparagus',
      'Radishes',
      'Beets',
      'Romaine',
      'Arugula',
      'Mixed Greens',
      'Ginger',
      'Cilantro',
      'Parsley',
      'Basil',
      'Dill',
      'Green Onions',
    ],
    'Dairy': [
      'Milk',
      'Eggs',
      'Butter',
      'Cheddar Cheese',
      'Mozzarella Cheese',
      'Yogurt',
      'Cream',
      'Sour Cream',
      'Greek Yogurt',
      'Cottage Cheese',
      'Half & Half',
      'Heavy Cream',
      'Parmesan Cheese',
      'Feta Cheese',
      'Swiss Cheese',
      'Provolone',
      'Cream Cheese',
      'Buttermilk',
    ],
    'Bakery': [
      'White Bread',
      'Whole Wheat Bread',
      'Buns',
      'Bagels',
      'Tortillas',
      'Croissants',
      'Muffins',
      'Sourdough Bread',
      'Rye Bread',
      'Pita',
      'Naan',
      'English Muffins',
      'Ciabatta',
      'Baguette',
      'Donuts',
      'Pie Crust',
    ],
    'Meat': [
      'Chicken Breast',
      'Ground Beef',
      'Pork Chops',
      'Bacon',
      'Sausages',
      'Steak',
      'Chicken Thighs',
      'Whole Chicken',
      'Ground Turkey',
      'Turkey Breast',
      'Ham',
      'Lamb Chops',
      'Roast Beef',
      'Hot Dogs',
    ],
    'Seafood': [
      'Salmon',
      'Shrimp',
      'Tuna',
      'Tilapia',
      'Cod',
      'Crab',
      'Lobster',
      'Scallops',
      'Mahi Mahi',
    ],
    'Frozen': [
      'Frozen Vegetables',
      'Frozen Pizza',
      'Ice Cream',
      'Frozen Berries',
      'Chicken Nuggets',
      'French Fries',
      'Frozen Corn',
      'Frozen Peas',
      'Frozen Spinach',
      'Frozen Waffles',
      'Frozen Meals',
      'Frozen Dumplings',
    ],
    'Snacks': [
      'Chips',
      'Crackers',
      'Popcorn',
      'Nuts',
      'Granola Bars',
      'Cookies',
      'Chocolate',
      'Pretzels',
      'Trail Mix',
      'Beef Jerky',
      'Salsa',
      'Hummus',
      'Rice Cakes',
      'Pita Chips',
    ],
    'Beverages': [
      'Water',
      'Soda',
      'Juice',
      'Coffee',
      'Tea',
      'Sports Drink',
      'Sparkling Water',
      'Almond Milk',
      'Oat Milk',
      'Coconut Water',
      'Energy Drink',
      'Lemonade',
      'Iced Tea',
    ],
    'Household': [
      'Paper Towels',
      'Toilet Paper',
      'Dish Soap',
      'Laundry Detergent',
      'Trash Bags',
      'Sponges',
      'Hand Soap',
      'Aluminum Foil',
      'Plastic Wrap',
      'Food Storage Bags',
      'Napkins',
      'Tissues',
      'Dishwasher Pods',
      'Bleach',
      'All-Purpose Cleaner',
      'Light Bulbs',
      'Batteries',
    ],
    'Condiments': [
      'Ketchup',
      'Mustard',
      'Mayonnaise',
      'BBQ Sauce',
      'Hot Sauce',
      'Soy Sauce',
      'Salad Dressing',
      'Olive Oil',
      'Vinegar',
      'Relish',
      'Honey',
      'Maple Syrup',
      'Peanut Butter',
      'Jam',
      'Jelly',
      'Sriracha',
      'Hoisin Sauce',
      'Teriyaki Sauce',
      'Sesame Oil',
      'Tartar Sauce',
    ],
  };

  static List<String> categories() {
    final list = itemsByCategory.keys.toList();
    list.sort();
    return list;
  }

  static List<String> itemsForCategory(String category) {
    final list = List<String>.from(itemsByCategory[category] ?? const []);
    list.sort();
    return list;
  }

  static const List<int> quantityOptions = <int>[
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
  ];
}
